### ISSUE TITLE
Theme Name

### ISSUE THREAD

**Issue by vinimatias** [BoldGrid/prime#1]
Please, change the theme name, because the same was in conflict with another wordpress theme. And the default uri on style.css was broken.
Theme URI: https://www.boldgrid.com/prime

**Comment by timelsass** [comment]
Hey vinimatias,
I'm aware of this issue when it comes to upgrades of this theme as it will pull the wp.org info in updates. Was this what you're referring to?

Internally we use this theme as a parent theme, and then each of the children repos are built and turned into parent themes for our distribution channels.  This was users can create their own children based off our child themes.  We didn't necessarily intend for this theme to be distributed in the .org repo, and would encourage users of this to look at the gulpfile.js build process of creating their own child theme based off the parent - or delve deeper in creating your own parent theme and integrating the [BoldGrid Theme Framework](https://github.com/BoldGrid/boldgrid-theme-framework) to fit your own needs.

If you have the [BoldGrid Inspirations](https://github.com/BoldGrid/boldgrid-inspirations) plugin install - this is what currently handles the update channels for our themes.  For this particular theme since it's not a distributed theme, it will check the wp.org update data if you have our Prime theme installed and unset the update data so you don't end up overwriting this Prime theme with the wp-org version.  This would prevent you ending up with getting the wrong update data as an interim solution.

This is something I've been wanting to resolve, and I think the route we're leaning on is to include our update class for this theme in the prime build process.  This way if a theme developer or end user ends up grabbing this from the repo and installing it, they will receive the updates from the appropriate channel.

As it stands now to make this theme usable you still have to run through some sort of build process or manual setup to load the dependencies, so even if someone downloads the .zip they are going to get quite a few errors if they attempt to use this directly.  I threw together [some docs on the install process](https://timelsass.github.io/install) if you need to reference it.

I haven't had an opportunity to document the child theme creation process or setup some official docs over here yet, and I was planning on creating a proper distribution .zip for github releases in our travis build.

I believe when we have this all done, it should take care of both of those issues and provide you with a better experience.  Does this sound like it would work out and resolve your particular use cases?

**Comment by timelsass** [comment]
For the time being - I updated the URL to reflect the github.com page until our website team is able to create a dedicated page for the Prime theme.

The build process now makes the final Prime theme available, so you can install this by getting the [latest version from the releases tab](https://github.com/BoldGrid/prime/releases/latest).

This is packaged as [boldgrid-prime.zip](https://github.com/BoldGrid/prime/releases/download/1.4.2/boldgrid-prime.zip) (v1.4.2 is the latest at the time of this response) - so you won't get the conflict for updates with the "prime" theme from the WordPress themes repo.  Any new releases will now be available to download in this section with the full theme available.
