### ISSUE TITLE
Shop page title 

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/prime#37]
The title from the Dashboard appears in and below the breadcrumb nav, and I have no idea where the text in the actual Page Title area is coming from. I feel like it should say Shop where it says Archive: Products and Shop should not appear below the breadcrumb.
![shop-page-title](https://user-images.githubusercontent.com/20601160/50642113-30a1b500-0f38-11e9-85ba-2b8391200f6e.PNG)

**Comment by timelsass** [comment]
That's perfectly fine to do.  Every user can customize their site as they see fit.  It's not uncommon to create special pages for displaying archives.

**Comment by nicolepaschen** [comment]
How do I get rid of that message on the Shop page? The Archive banner? It should not show to end users and right now it does.

**Comment by timelsass** [comment]
This is repo is not a support forum for WooCommerce or WordPress, I would suggest asking in support forums related to one of those as to how to change an archive description.

**Comment by nicolepaschen** [comment]
So every Crio user will need to do that?  It seems like the theme should just hide that. It's the main Shop page that comes standard with WooCommerce, I've never seen that Archive heading shown in other themes.

**Comment by timelsass** [comment]
> So every Crio user will need to do that? It seems like the theme should just hide that.

Yes, if a user does not wish to display the text they have entered in a particular location, then they would need to do something to change or hide that text.

> It's the main Shop page that comes standard with WooCommerce

There is not any "main Shop page that comes standard with WooCommerce."  The archive descriptions from the screenshot supplied though are added using the WordPress core function, [the_archive_description()](https://developer.wordpress.org/reference/functions/the_archive_description/).  These are displayed for any archive pages you link to on a site using this theme.

> I've never seen that Archive heading shown in other themes.

I'm sorry you haven't observed this previously in using other themes.  A lot of the top themes in the wp.org repo do display archive descriptions, [which can be confirmed in this search](https://wpdirectory.net/search/01D7ZA221JPVZ4Y3DFNT6BG6CC).

A few options on how this could be changed by a user:

1. You are more than welcome to [override any of the templates](https://developer.wordpress.org/themes/advanced-topics/child-themes/#adding-template-files) used in a child theme if you wish to never display archive descriptions, titles, or even specific [WooCommerce templates](https://docs.woocommerce.com/document/template-structure/).  This is a feature provided by WordPress core to allow further customization for users, and we recommend doing this instead of directly editing any of the files in the theme. The template responsible for the page header display on archive pages is already [it's own individual template](https://github.com/BoldGrid/prime/blob/2.1.0/templates/page-header-archive.php) to make it easier for users to override as they see fit.

2. In the past we have discussed adding features for users to modify individual category, archive, and tag pages with controls similar to what we offer for individual posts, but these types of features would be part of a plugin, and not really related to this theme (or WooCommerce) specifically.  It seems like something like that may be of more benefit to what you're wanting to do if you're not wanting to create a child theme to edit the templates provided.  There's several solutions that allow these types of changes available in the wp.org plugin repository today, so you could try using some of those.

3. As another alternative, you could also create your own custom pages in WooCommerce to display product listings as you desire.  WooCommerce has released block plugins for the editor to aide with this type of thing, and even their [products shortcode](https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-6) can come in handy for creating custom product listings for shop pages instead of using an archive page as shown in the screenshot you posted.

Ultimately every person's use case is a little different, our goal with Prime is to integrate WooCommerce features with our theme's layout and our theme framework.  We don't want this to make conditional decisions on how that information is displayed based on whatever plugins might be installed and active.

**Comment by nicolepaschen** [comment]
> Yes, if a user does not wish to display the text they have entered in a particular location, then they would need to do something to change or hide that text.
This text displays even though I did not enter it anywhere. Brad and I both looked in the dashboard and cannot find where it is coming from. Can you please show us?

> There is not any "main Shop page that comes standard with WooCommerce."
I have to set a Shop page here, this is the page I am referring to:
![image](https://user-images.githubusercontent.com/20601160/55764465-9a4ec500-5a39-11e9-843d-0ff4142dc4bb.png)

**Comment by timelsass** [comment]
> This text displays even though I did not enter it anywhere. Brad and I both looked in the dashboard and cannot find where it is coming from. Can you please show us?

That is true.  I'm not saying you or even someone named Brad are responsible for entering the text displayed anywhere, just that any text that is entered for ouput to be displayed in a particular location would be displayed unless a user changes that.  How it gets there or what to change can vary depending on whatever location we're talking about.  In this case we're talking about the_archive_description(), so I provided options 1, 2, and 3 above on how you could resolve this for your site's own needs.

There was no mention of doing anything within context of a dashboard, nor saying you caused this text to be entered.   I'm not entirely sure I understand the further questions given my previous response though.  Are you perhaps suggesting that of the 3 recommendations provided you're not willing to try one of those to modify the look and feel of the page in question, but are continuing to search for an alternative solution?  If that's the case, that's definitely fine to do as well, but unfortunately this would be further out of scope from what would be handled by our Prime theme.

> I looked at the link and the first theme was 2017. I do not see this heading in 2017

I'm not familiar with what that theme, or really any other themes do in terms of hiding or displaying something.  I'm just simply showing that other themes do make use of [the_archive_description()](https://developer.wordpress.org/reference/functions/the_archive_description/), and have explained why we use that function in our template for archive headers.  As stated in my previous comment, everyone's use case _is a little different_, but with the 3 solutions provided above, there shouldn't be any reason why you can't make this section appear just the way you want it to!

Previously I had mentioned:
> "Our goal with Prime is to integrate WooCommerce features with our theme's layout and our theme framework. We don't want this to make conditional decisions on how that information is displayed based on whatever plugins might be installed and active."

Just to make sure I'm being clear, I don't disagree with what your needs are, or any perceived issues stated here.  The issue though came down to how to change something you think should be changed.  We encourage everyone to explore their creativity, and is part of philosophy behind a lot of our plugins and themes.  Everyone is entitled to create their site just how they like, which is why WordPress is a popular choice to build upon!  Part of the philosophy that has contributed to WordPress' success is that themes and plugins do have to make decisions though, not provide options for everything.  Too many options, and things get confusing and cluttered, not enough and things are hard to get just right.  It's about finding just the right balance, which is something we try hard to achieve in our themes and framework.  I will mention here that one of the proposed features that we have discussed as a team outside of GitHub itself was adding controls for archives, categories, tags, their titles & descriptions, along with allowing featured images for those types of pages.  This would help in customizing all of these things independently, and provide similar controls that we provide for things like Pages and Posts to other areas of WordPress that are commonly displayed in a site.  From the struggles mentioned in this issue, I believe this would help address your particular issues of handling changing this information in a more "visual" way if you're not comfortable making changes to your site's templates and/or creating a child theme.  Unfortunately, I do not have any ETA on when this feature would be implemented as previous discussions we have had have not yielded much interest or use cases for our users.  It is however something that is on our radar to help provide a better user experience, not just for WooCommerce as a plugin, but all plugins which provide a similar experience.  While the recommended 3 options provided aren't hard to implement, they really are just one-off changes that are only specific to "WooCommerce" as a plugin in this case.  We'd much rather implement a solution that addresses the root of the issue for all plugins that make use of these features.

Generally speaking, we do try our best to make sure to address any issues in relation to development here, and are always open to new ideas, issues, and discussions.  Just keep in mind that a closed issue doesn't mean that something is any more or less of an issue, so don't let a closed issue discourage you.  There's never any bad ideas or new feature requests, but we sometimes have to decide what we feel is best in terms of what we do chose to support.  It simply means we might have alternative solutions being worked on, other issues that are addressing the same concerns, or even something we consider to be out of scope for a project.   We do offer support for our themes and plugins at boldgrid.com, which is a more open ended type of forum not geared towards development, and can assist you with issues that are similar to this one.  Hopefully this helps in understanding how to achieve your desired results using Prime and what our intentions are with when it comes to themes and plugin support.  If anything I hope this helps at least provide some clarity and further insight as to why this issue is closed if there's any further confusion on this topic.
