### ISSUE TITLE
Product Image shouldn't show as Featured Image

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/prime#38]
There is no input for a ‘Featured Image’ on a product and right now the Product Image is used in the Page Title background when it should not.
![product-featured-image](https://user-images.githubusercontent.com/20601160/50642198-69418e80-0f38-11e9-8fb9-b2d7a8f36332.PNG)

**Comment by timelsass** [comment]
WooCommerce is a WordPress plugin, which creates a custom post type called Products.

From their documentation as to what the post's images are for Products - they state: "A Single Product Image is the largest image and refers to the main/featured image on your individual product details page."

If a user has customized their site to include featured images as backgrounds to post titles, then it applies to posts, like products, jobs, portfolio, etc.  This provides consistency in design across a site with dynamic content.

In the future controls per page/post may be able to be leveraged to provide more flexibility on a per post/page basis, but this functionality should belong inside of a plugin as it's code wouldn't be theme specific (I believe there's already a lot of plugins out there which do this as well, so it might not be something we need to address).

Reference to woocommerce docs: https://docs.woocommerce.com/document/adding-product-images-and-galleries/#section-1

**Comment by nicolepaschen** [comment]
there is no image that will look good as both the Product Image in a column and the background on the page title. What should an end user do?

**Comment by timelsass** [comment]
> there is no image that will look good as both the Product Image in a column and the background on the page title.

I'm sorry to hear that you are having issues finding images that look good as both a featured image header, and as a product image.  There's plenty of sites that do set featured images as a background to a heading/title container, and still use the image within their post's content - it's a pretty common design pattern in WordPress themes!  I generally find that choosing large images that showcase the product well as my product image usually look best as the backgrounds for the titles, and make for good display images in the product's image gallery.

> What should an end user do?

Aside from things mentioned in my previous comments, there's various other ways you can handle this:

1. If you're not satisfied with the look and feel of a particular template, you're welcome to create a child theme to override this page title's featured image background, by creating your own template.

2. You can override [the default configuration value](https://github.com/BoldGrid/prime/blob/2.1.0/inc/boldgrid-theme-framework-config/config.php#L506) which is setting the display of this area.  Generally recommended to do this from a child theme as well in `functions.php`.

3. If this isn't something you are comfortable doing, we also provide a premium plugin + support for themes based on Prime.  The plugin allows you to display featured images on posts in other ways instead of always setting them as the background images for the post titles.

**Comment by nicolepaschen** [comment]
> so it might not be the best image to use for that area.

I agree. Please show me in the dashboard how to have a product with a product image but no featured image, or a featured image that's different from the product.

**Comment by timelsass** [comment]
> I agree. Please show me in the dashboard how to have a product with a product image but no featured image, or a featured image that's different from the product.

Please show me in the conversation where I ever mentioned that there is a step to go to the dashboard and do anything... When have you ever gone to the dashboard to do something dealing with featured images in the first place?  Did you read my first comment on why this issue was closed? It sounds like you might be stuck on how WooCommerce handles things, and have just gone around in a full circle with reasons that are unclear to me right now.  I'm not able to explain that any differently than I did, but I did cite their documentation in that response which is much more informative if you're still unsure.

To get back on topic with Prime, it sounds like you are still lost or uncertain as to what steps you should take.  You refused to acknowledge **_the very clear numbered list which has 3 solutions presented to you on how you can change the behavior for your site_**, so I'd suggest that again.

If you have expectations for me to answer followup questions that are void of any comprehension or acknowledgement to previous parts of our discussion, then there's really nothing left for me to offer you by continuing this discussion, or by you asking further questions.  You've been unwilling to read the answers provided that undoubtedly show that I have been trying to take your concerns seriously, and have been investing my time in trying to be comprehensive in my responses for you AND others to benefit from, what more can be really be expected here..  If your intention is to try and have this issue  reopened, that's not really your decision to make, especially when I have provided you with the answers, reasoning, and justification for not being willing to make this change.  I can only assume at this point, this is just a troll because you've flat out ignored each response I give and counter it with something random and unrelated.

I have honestly done nothing but try to promote healthy discussion on both open and closed issues to help provide direction and clarity when needed, but I will no longer be able to extend this courtesy to you once an issue is closed.  This has gone beyond any sort of reasonable or healthy discussion, and is a _**crystal clear**_ example of **_harassment_** through online mediums.  While to a certain extent dealing with an occasional troll is sometimes considered "part of the job", it's really not part of any job to deal with harassment from internal sources.  It's not okay to troll on issues, ignore the actual responses, ask irrelevant questions, or in the case of your last response, just make up random expectations completely.  I have been more than patient, and courteous in my responses, but it's also very clear that I am the only one really trying to make any effort here.  I've done nothing but try helping you understand why something is closed so others can understand as well if they happen to end up here, but when that courtesy and respect isn't given back, then really anything past the issue being closed does not warrant any further response from me from now on.  

Childishly reopening issues continuously after they are closed by a maintainer/lead on a project after they have taken time to provide a detailed and valid set of reasons is extremely immature and unprofessional and makes not just this repository look bad, but reflects negatively on the organization it's under.  The whole purpose seems to be just driven on asking questions that aren't even relevant to why the issue is closed, but still it's been mentioned several times in the past that closed issues can still be commented on.  This is why I have removed your rights on this repository and boldgrid-theme-framework.  If you're not willing to trust my judgement while maintaining this project, or understand some of the basic concepts in our code base - then I honestly can't allow you to make changes to issues or code in good conscience using ways that were previously available to you.  Both new issues and contributions are still more than welcome, but your commits will need to come through pull requests now as direct commit access is also revoked with this change.  I expect other developers that are maintainers/contributors to projects to treat me this same way.  If they feel like I lack understanding in a particular area, and can't make the right judgement, they disregard my input and do what is best for their responsibilities.  I could give dozens of examples in our own repos, because I don't know everything, and I don't spend time doing everything either.  This isn't meant to be discouraging, but informative.

Issues (open and closed) are a big source of reference for others when they run into their own problems, so I do try and make it a point in my responses to go further by providing actual reference to sources so others can learn about any functions referenced, or resources that would help them learn about certain concepts that are required to be understood to comprehend why a decision is being made when it's applicable.  This is a big reason why I pushed for transitioning our workflows to GitHub issues in the first place, so others could engage with us, and help create more transparency with decisions that are made.  Having disputes like this repeated from within our own team gives an impression that we aren't very open or willing to have outside collaboration.  There's absolutely no reason why I should need to go beyond my first comment's explanation to explain or justify my decision, but in the event where what I've said could be misconstrued or perhaps unclear - then I have been understanding that sometimes there's gaps in communication online.  I have continuously given the benefit of doubt, and tried to help you see and/or understand because I care about this project, the people involved, and the direction it takes.  I care about other's opinions and value them, but sometimes decisions have to be made, and those aren't ever meant to be spiteful, or negative, but it's unrealistic to think that every decision made is going to please every party involved or every issue raised based on opinion will be implemented.  I spend countless hours outside of what is my "defined job" in preserving these sentiments here, and try to embrace the same values outside of our own projects.  These values are really the only thing that make open source software sustainable, fun, and one of the most invaluable learning mechanisms for developers of any level.

This response isn't something I take lightly, or just randomly blurting out.  In reviewing this issue, I do still feel that _**any developer**_ would be able to read the original question asked, and without a doubt understand based on my response why the issue was closed.  If I didn't care about educating others, or this project, I would simply just close any issue that is opened with "wontfix" and not provide explanation.  It's not a requirement for me to provide further reasoning, but it's something that I personally believe is a good practice to share the knowledge we each have, and share insight as to why a decision is made and either let others deduct why that's the best decision or flat out say why it's the decision you think is best.  Collaborators to this project don't have to agree with every decision that's made, and if that were the case nothing new or different would really every happen here.  We continuously have open discussions to encourage input from various parties, and you're welcome to have opposing views.  Healthy discussion is/has always been encouraged, but there's absolutely nothing constructive coming from these retaliative responses which we both know only serve the purpose of wasting time and reopening an issue you are opposed to being closed.  I can't continue to encourage this type of childish behavior in any open or closed mediums we have with each other because it ultimately means I fall behind in what is expected of me here and in other places.  Others are more than welcome to participate in conversation on closed issues with you if they wish, but this has really become a continuous problem between us, and while I don't care much one way or another on what people think about me, I do actually care about myself. Having a feeling that I have a constant target on my back and am continuously asked to justify decisions, and provide response to things like this is not beneficial towards my own self-awareness.   I think it's best for me to just remove myself from this equation, and you can seek further assistance and answers from anyone else willing to reply to you. 

You're still invited, and welcome to create new issues as well as participate in discussions, but I can't tolerate or entertain this level of harassment any longer.  We all have to deal with closed issues daily, you're not alone.  I feel pretty confident saying that everyone who contributes code to projects is familiar with this level of rejection, reminded of compromises we have had to make, and knows the frustration that can be involved.  When that happens we have to trust the maintainer or lead of the project, and know that they are going to be more familiar with the codebase and intricacies involved to make a better informed decision to help get a project where it needs to go.  Sometimes they make the wrong decision, more often than not they make the _best_ decision, nobody is perfect, but this should never lead to the behavior displayed here as being considered an acceptable response.  My apologies if this isn't the response you were hoping for or if you feel like I've misinterpreted your intentions, but I think this will help make our expectations from each other clear as there may have been some sort of misunderstanding.
