### ISSUE TITLE
Feature: Add option to disable post title display on the blog page

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/prime#47]
**Is your feature request related to a problem? Please describe.**
If a user chooses to hide their post title and create a new title as part of the post content using the Post and Page Builder the title still displays on the main Blog page.  This leads to the title displaying twice in the blog reel, once as the "entry-title" and again as part of the actual post content.

**Describe the solution you'd like**
Add an option in the Customizer to toggle post title display for the Blog page.

**Comment by timelsass** [comment]
No, the user should enter a title that's relevant, and not do that.

**Comment by timelsass** [comment]
Ehm, going to have to say no on this for now.  The problem with this approach is kinda two fold of supporting WordPress core vs supporting a third-party editor plugin.  It's no specific to just page titles on a "blog", but all page titles when used in dynamic content.

From the principal of things - all pages should have a page title.  Everyone pretty much agrees on this.  A third-party plugin and poor decisions on implementing a design forced adding a control to offer a "hide page title" to the classic editor in WordPress.  It was a bad idea that I repeatedly spoke out against, but was continuously countered for no reason.  It's there, but it's worthless to ever use.  We can't just filter all page titles of a certain to not display in a very logical way, because we want them to display in certain contexts, but not others.  It's not entirely feasible to predict all the context in which that particular post title might display, which is why blogs and single posts suck in v1 because for some reason "dynamic content" doesn't exist to anyone's mind.

It's also a VERY disjointed experience overall, which makes absolutely no sense from a user's standpoint.  Why would a user _not_ enter a page title, and add one inside of the content?  They shouldn't.  Mostly because common sense tells you it makes no sense.  Aside from that, now the administrative side has no descriptive way for a user with posts and pages to identify which pages and posts they want to edit without requiring them to click on it and see which it is.  The editor (Gutenberg, and the BoldGrid Editor + TinyMCE) is one of the most resource expensive and time consuming processes that run.  Requiring users to figure out which page is what because they hid their page title on the front end, and have something else saved as the title is bad.  On top of this, when creating pages and posts with pretty permalinks on, the slugs are generated off of your page title.  This helps increase better SERP placements because the slug is descriptive to the content.  

Take a look at Gutenberg as a better example:
![image](https://user-images.githubusercontent.com/11907254/58212265-37994c00-7cbc-11e9-8a5e-230e462aa667.png)

The title is inline in the "editor", so the when they click edit they are also editing the slug.

Having something like 'test-page-7' as a slug, with a title of "Test Page 7" it's still getting picked up in an archive still as "Test Page 7" being the title in context of a search as the titles require certain classes to be added in order for metadata to be properly read.  All in all, if a user wants to "add a title in their post" - they are hurting themselves for no reason, and we shouldn't encourage bad design or SEO for that matter.
