### ISSUE TITLE
WooCommerce template out of date with Crio 2.2.7 & Woo 3.7

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/prime#55]
crio/woocommerce/myaccount/orders.php version 3.2.0 is out of date. The core version is 3.7.0, 

Please update this template so the warning doesn't show on the wp-admin dashboard.

Thanks!

**Comment by timelsass** [comment]
Thanks!  Yeah, it looks like the most recent changes were changes to code formatting and language strings, which doesn't break any functionality.  That's good, but it won't be something urgent since Crio was updated recently, but we will definitely get it included in the next release!  The notice for the woocommerce template files for that build should only display when debug is on, so the majority of users with live sites shouldn't see that as debug shouldn't be left on in production.  

We might be able to deprecate this template, but I'll need to investigate further.  Getting rid of reliance on template overrides is always more preferable for us in the long run so we don't have to maintain the template if hooks are included, or the BGTFW v2 has styles that address elements that needed to be modified!

Feel free to submit a PR if you get to it before I do, and I can merge it in.  I am going to close this issue though in favor of https://github.com/BoldGrid/prime/issues/33 since the work needs to be tested on old and new versions of BGTFW.  Usually both old and new themes are updated at the same time, but old themes are an update behind since the newer ones were undergoing review for the release to wp.org themes repo.  They all need to be caught up to the latest though!
